### ISSUE TITLE
Inference of base-type for boolean database-type columns not working

### ISSUE THREAD

**Issue by s-huk** [ClickHouse/metabase-clickhouse-driver#133]
This issue might be related with issue #88

Inference of base-type for boolean database-type columns is still not working. Given a boolean column with database-type "Bool", the base-type metadata is recognized as :type/* instead of :type/Boolean (e.g. see GUI-->Admin-->DataModel-->Table-->Original schema).

I will propose a PR with fix and tests to solve this issue...

**Comment by slvrtrn** [comment]
@s-huk released as https://github.com/ClickHouse/metabase-clickhouse-driver/releases/tag/1.0.1
