### ISSUE TITLE
An option to make all tables from all databases (except system ones) visible in Metabase

### ISSUE THREAD

**Issue by slvrtrn** [ClickHouse/metabase-clickhouse-driver#137]
Previously, with the past Metabase and JDBC driver versions, it did not really matter which database a user was connected to - all the tables from all the databases were visible.

After Metabase and JDBC driver upgrades, the driver works in line with the other solutions - the tables are displayed only from the connection database.

However, many users reported that they prefer the legacy behaviour where everything is always visible, and all the tables from all the databases are accessible and not limited to the connection database. See https://github.com/ClickHouse/metabase-clickhouse-driver/issues/121 for additional context.

The proposal is to investigate how to bring back this workaround 

https://github.com/ClickHouse/metabase-clickhouse-driver/blob/91b523a6e00f4c6f15d4afb239c48151ff316d5b/src/metabase/driver/clickhouse.clj#L508-L517

that does not seem to work anymore (the method is called only with the connection database) via some kind of a UI toggle ("scan all databases" switch or leave the dbname empty?).

**Comment by djuarezg** [comment]
https://github.com/ClickHouse/metabase-clickhouse-driver/releases/tag/1.0.3 does not address this, does it?

**Comment by slvrtrn** [comment]
@djuarezg 1.0.4 should have it.

Please stay tuned.

**Comment by slvrtrn** [comment]
@djuarezg please try [1.0.4](https://github.com/ClickHouse/metabase-clickhouse-driver/releases/tag/1.0.4) with the new "Scan all databases" toggle. See https://github.com/ClickHouse/metabase-clickhouse-driver/pull/143 for more details.

**Comment by djuarezg** [comment]
@slvrtrn It works flawlessly, as always, thank you very much for your work.
