### ISSUE TITLE
Commenting with `--` doesn't work well when using parameters.

### ISSUE THREAD

**Issue by AndresElizondo** [ClickHouse/metabase-clickhouse-driver#146]
### Describe the bug
When writing a query that uses parameters, you'd expect to be able to comment out a line and have the query run as if the line didn't exist. In reality, the preprocessor tries to do something with the commented parameter and the query crashes.

### Steps to reproduce
1.Write a query that uses parameters
```
select 'hello'
where 'world' = {{worldParam}}
```
If we feed the value `world` to the parameter `worldParam` his query will run with no issues.
2.Comment the where clause using `--` (double dash).
```
select 'hello'
-- where 'world' = {{worldParam}}
```
This query will crash with the error:
`Can't set parameter at index 1 due to no JDBC style '?' placeholder found in the query`

We can also try setting more params:
```
select 'hello'
where
 'there' = {{worldParam}}
--  and 'world' = {{worldParam}}
```

This query now crashes with error:
`Parameter index must between 1 and 1 but we got 2`

Note: Running this query directly in Clickhouse works correctly.

3. Change the comment to use `#!` instead of `--`
```
select 'hello'
where
 'there' = {{worldParam}}
#!  and 'world' = {{worldParam}}
```
The query now runs as expected.

### Expected behaviour
The query should behave the same with any type of comment `--`, `#` or `#!`.

#### Environment
* metabase-clickhouse-driver version: 1.1.0
* metabase-clickhouse-driver configuration: <not sure>
* Metabase version: 0.45.3

**Comment by paoliniluis** [comment]
This is an issue of Metabase, we're fixing it on v46
