### ISSUE TITLE
Specify multiple schemes on connect

### ISSUE THREAD

**Issue by veschin** [ClickHouse/metabase-clickhouse-driver#151]
**New feature**
It would be great to be able to select multiple schemas when connecting a data source

![image](https://user-images.githubusercontent.com/49994326/227168078-ff87454f-a30e-4f62-b529-a26795f9a44b.png)

**Comment by slvrtrn** [comment]
Released as [1.1.3](https://github.com/ClickHouse/metabase-clickhouse-driver/releases/tag/1.1.3)
