### ISSUE TITLE
Migrate the driver code to HoneySQL2

### ISSUE THREAD

**Issue by romubaronvp** [ClickHouse/metabase-clickhouse-driver#153]
### Describe the bug
When starting Metabase 0.46.0, I'm getting the following error:
`Driver :clickhouse is using Honey SQL 1. This method was deprecated in 0.46.0 and will be removed in a future release`

### Steps to reproduce
1. Install Metabase 0.46.0 with latest metabase-clickhouse-driver
2. Check in the log and you'll get the above error

#### Environment
* metabase-clickhouse-driver version: 1.1.3
* metabase-clickhouse-driver configuration: None
* Metabase version: 0.46.0
* OS: Debian

#### ClickHouse server
* ClickHouse Server version: 23.2.3.17

**Comment by romubaronvp** [comment]
I bumped into this page which mention that "the process for building a driver has changed slightly in Metabase 0.46.0"
https://www.metabase.com/docs/master/developers-guide/driver-changelog

**Comment by slvrtrn** [comment]
Thanks for opening an issue. I forgot to open one as there are ongoing efforts in the `honeysql2` branch; those are just incomplete yet.

I will rename it and keep it open for now until the branch is merged.

**Comment by zxpower** [comment]
Just upgraded to MB v0.46.6.1 with CH driver v1.1.7 and still have the same warning.

**Comment by slvrtrn** [comment]
@zxpower, this will be resolved with the driver release that supports Metabase 0.49 - that version will replace HSQL1 with HSQL2 completely.
