### ISSUE TITLE
`Sum If` cannot be applied to `Int` Columns

### ISSUE THREAD

**Issue by pulsar256** [ClickHouse/metabase-clickhouse-driver#156]
### Describe the bug

applying `Sum If` expression in Metabase to `Int` columns will generate invalid SQL

#### Given Schema 
```sql
create table public.sum_if_test
(
    id            Int64,
    int_value     Int64,
    discriminator String
) ENGINE = MergeTree()
      primary key (id, discriminator);
```

#### Given Test Data

```sql
insert into public.sum_if_test values (1, 1, 'foo');
insert into public.sum_if_test values (2, 1, 'foo');
insert into public.sum_if_test values (3, 3, 'bar');
insert into public.sum_if_test values (4, 5, 'bar');
```

#### Given Metbase Report Configuration

custom expression configured in Metabase when summarizing this table:

![image](https://user-images.githubusercontent.com/1245126/236408739-630f6c19-9969-4ae5-ab58-782f3d81824d.png)

Will generate SQL:

```sql
SELECT sum(CASE WHEN `public`.`sum_if_test`.`discriminator` = 'bar' THEN `public`.`sum_if_test`.`int_value` ELSE 0.0 END) AS `sum_if_with_int`
FROM `public`.`sum_if_test`
```

using a float `0.0` default value instead of `0` in `ELSE 0.0`

### Expected behaviour

`Sum If` expression can be applied to `Int` typed columns

### Error log

```
ode: 386. DB::Exception: There is no supertype for types Float64, Int64 because some of them are integers and some are floating point, but there is no floating point type, that can exactly represent all required integers: While processing if(discriminator = 'bar', int_value, 0.). (NO_COMMON_TYPE) (version 22.8.15.1) , server ClickHouseNode [uri=https://(...)/public, options={use_server_time_zone_for_dates=true,use_no_proxy=false,product_name=metabase/1.1.2}]@92216918
```

#### Environment
* metabase-clickhouse-driver version: 1.1.2
* Metabase version: v0.46.2
* OS: Linux

#### ClickHouse server
* ClickHouse Server version: 22.8.15

**Comment by slvrtrn** [comment]
@pulsar256, could you try 1.1.4? It should work there now.

**Comment by pulsar256** [comment]
@slvrtrn thank you for the fix! I have just deployed the new version and it seems to be working now.

**Comment by slvrtrn** [comment]
Glad that it worked!
