### ISSUE TITLE
Release cycle

### ISSUE THREAD

**Issue by sharat910** [ClickHouse/metabase-clickhouse-driver#159]
Is there a planned release cycle? The last release seems to be from a few months ago and there are some new features/bug fixes since then that can be released.

**Comment by slvrtrn** [comment]
Hi @sharat910, I just released 1.1.4 (see #157)

There is no planned release cycle yet - I tend to release a new version right after a new feature or bug fix is ready.

> there are some new features/bug fixes since then that can be released

Please, feel free to bump these issues for visibility - it helps to prioritize.

Additionally, contributions from the community are very welcome, and I tried to compose a helpful [contribution guide](https://github.com/ClickHouse/metabase-clickhouse-driver/blob/master/CONTRIBUTING.md). 

Last but not least, don't hesitate to post your question in our [community Slack](https://clickhouse.com/slack) in `#help` or even ping me there directly.
