### ISSUE TITLE
Broken: Driver does not work with the latest metabase release (0.46.3)

### ISSUE THREAD

**Issue by dodg3this** [ClickHouse/metabase-clickhouse-driver#161]
### Describe the issue

The driver fails to sync the database after upgrading the metabase to 0.46.3

### Steps to reproduce
1. Upgrade metabase to 0.46.3
2. Add Clickhouse database

### Expected behaviour

Syncing should be successful

### Error log

`java.lang.IllegalStateException: Attempting to call unbound fn: #'metabase.util/snake-key`

#### Environment
* metabase-clickhouse-driver version: 1.1.4
* Metabase version: 0.46.3

**Comment by dodg3this** [comment]
False alarm. The issue is with the master branch. So may have to fix it later when it gets released.

**Comment by paoliniluis** [comment]
Testing the latest driver (1.1.7) with 1.47.0-RC1 returns this error and the DB does not sync correctly

**Comment by slvrtrn** [comment]
@paoliniluis, IIUC, for 0.47, we need to merge https://github.com/ClickHouse/metabase-clickhouse-driver/pull/160 first.
