### ISSUE TITLE
Creating connection to Clickhouse AST Error

### ISSUE THREAD

**Issue by porteron** [ClickHouse/metabase-clickhouse-driver#168]
### Describe the bug
We have the Clickhouse driver installed on our metabase instance. When click Submit when attempting to create a new db connection in the Metabase Admin we are prompted with an AST too big error:

```
Code: 168. DB::Exception: AST is too big. Maximum: 100. (TOO_BIG_AST) (version 22.3.10.24.altinitystable (altinity build)) , server ClickHouseNode 
```

Any guidance on how we can successfully create the connection? 

Metabase version `0.46.2`

**Comment by slvrtrn** [comment]
It is probably not related to the driver cause there is a server setting that needs to be adjusted: https://clickhouse.com/docs/en/operations/settings/query-complexity#max-ast-elements
via user profiles (see https://clickhouse.com/docs/en/operations/settings/settings-profiles for more details).

**Comment by porteron** [comment]
Yes that was the issue. The readonly user we created had the config `<max_ast_elements>100</max_ast_elements>`. Updating it to the default fixed the issue. Thank you @slvrtrn
