### ISSUE TITLE
Filter Custom Expression fails for week/now combination

### ISSUE THREAD

**Issue by Tony-metabase** [ClickHouse/metabase-clickhouse-driver#185]
### Steps to reproduce
1. New -> GUI Question -> Select Table -> Filter on Custom Expression -> `week(now`

<img width="1455" alt="image" src="https://github.com/ClickHouse/metabase-clickhouse-driver/assets/110378427/e085ed73-88ed-4a56-8754-3e7d8080b6ef">

2. Click Enter - It fails

<img width="1507" alt="image" src="https://github.com/ClickHouse/metabase-clickhouse-driver/assets/110378427/594cbff1-2332-4224-a0b6-e7dc26240086">

### Expected behaviour

I am able to click now()

### Error log

Only frontend logs:

<img width="1506" alt="image" src="https://github.com/ClickHouse/metabase-clickhouse-driver/assets/110378427/f61804d3-3758-4039-b370-f9f6ed106dd8">

#### Environment
* metabase-clickhouse-driver version: 1.1.7
* Metabase version: 1.46.6.4

#### ClickHouse server
* ClickHouse Server version: latest - yandex/clickhouse-server

**Comment by slvrtrn** [comment]
is it working with something like `week(now()) > 30`?

**Comment by Tony-metabase** [comment]
Yes indeed it does but the issue is that it break the whole screen when you start typing `week(now` and prompt to do an enter? 

It doesn't happen on any other DB i am connected with (MYSQL, Snowflake, PGSQL)

**Comment by slvrtrn** [comment]
Could you test it with MB 0.47-RC2 and driver version 1.2.0? It is working fine there, as everything shows up correctly. It might have been related to #178 (we generally had suboptimal base type inference prior to 1.2.0).

The last suspicious thing is `latest - yandex/clickhouse-server`. It is deprecated, and you should use https://hub.docker.com/r/clickhouse/clickhouse-server

**Comment by Tony-metabase** [comment]
The issue seems to be the version. Tried on 0.47-RC2 and version 1.2.0 and wasn't able to replicate
