### ISSUE TITLE
Inconsistencies in booleans handling

### ISSUE THREAD

**Issue by mlazowik** [ClickHouse/metabase-clickhouse-driver#189]
### Describe the bug

I'm not 100% sure whether this should be here, or in Metabase repo, but my bet is here.

When using the notebook with boolean questions:
* the "original schema" type inferred by Metabase is `type/Boolean`, same as when using Postgres
* the semantic type is "Category", same as when using Postgres 
* when selecting the column from the list in the notebook it has the `Aa` icon, while in Postgres it has `I/O`
<img width="379" alt="Screenshot 2023-08-31 at 16 26 11" src="https://github.com/ClickHouse/metabase-clickhouse-driver/assets/1978721/3135e993-4da6-49cf-a596-327560ed4b44">
<img width="225" alt="Screenshot 2023-08-31 at 16 26 56" src="https://github.com/ClickHouse/metabase-clickhouse-driver/assets/1978721/78d6d207-e069-4841-9064-950d44be0478">

* the filtering interface for ClickHouse seems to be generic category one, in Postgres it's dedicated to booleans
<img width="293" alt="Screenshot 2023-08-31 at 16 27 39" src="https://github.com/ClickHouse/metabase-clickhouse-driver/assets/1978721/fe669b64-ad5b-4e04-95d3-adbb38e0532e">
<img width="237" alt="Screenshot 2023-08-31 at 16 27 50" src="https://github.com/ClickHouse/metabase-clickhouse-driver/assets/1978721/690416fd-b836-47e3-bd89-afaab93a2282">

* it's possible to select boolean columns in `Sum of …` in ClickHouse, not possible in Postgres
* the result of summing over a boolean column in ClickHouse is treated as a textual result by Metabase, there is no option to set separator style etc.
<img width="285" alt="Screenshot 2023-08-31 at 16 29 33" src="https://github.com/ClickHouse/metabase-clickhouse-driver/assets/1978721/ba835658-7f75-4f77-88ba-5e09fd5e5170">
<img width="149" alt="Screenshot 2023-08-31 at 16 32 53" src="https://github.com/ClickHouse/metabase-clickhouse-driver/assets/1978721/45c479d8-1af8-4b20-ac7b-6032d4fe8b5d">

* It _is_ possible to select the number styling when either summing booleans in SQL, or using `CountIf()` instead of summing
<img width="313" alt="Screenshot 2023-08-31 at 16 33 33" src="https://github.com/ClickHouse/metabase-clickhouse-driver/assets/1978721/99d4b1ea-bee9-4520-b8a1-bd2cb3db810a">
<img width="81" alt="Screenshot 2023-08-31 at 16 34 08" src="https://github.com/ClickHouse/metabase-clickhouse-driver/assets/1978721/8d130419-0c51-43f2-b076-5d8147326d48">

* Notably formatting options are missing when using a notebook, but when you convert a question created using notebook to raw sql the options are there. Which seems to show that the problem is with how Metabase treats the results, not with the SQL query

IMO this is a problem, because non-technical users will reach for the `Sum of …` by default, and training them that they should avoid it and use `CountIf()` to get proper formatting will not be easy.

### Expected behaviour
Either summing over booleans is not supported in the graphical interface, or the result is understood by Metabase to be a number.

#### Environment
* metabase-clickhouse-driver version: `1.1.7`
* Metabase version: `0.46.7`
* OS: `NixOS 23.05`

#### ClickHouse server
* ClickHouse Server version: `23.7.4.5`

**Comment by slvrtrn** [comment]
I cannot reproduce it with CH 23.8/MB 0.47.2/Driver 1.21. Can you please check it with these versions? It could be due to 1.2.0 changes to [database types mapping rework](https://github.com/ClickHouse/metabase-clickhouse-driver/pull/181), though I am not sure.

```sql
create table test (b Boolean, s String) engine MergeTree order by b;
insert into test values (true, "foo"), (true, "bar"), (false, "qaz");
```

![image](https://github.com/ClickHouse/metabase-clickhouse-driver/assets/3175289/a77d6b8d-38e0-4d48-9e03-7b65f1a8ce37)

![image](https://github.com/ClickHouse/metabase-clickhouse-driver/assets/3175289/9974d230-caf9-4f02-8ad5-00f68945e150)
