### ISSUE TITLE
IPv4 field starts with dash

### ISSUE THREAD

**Issue by phuntik** [ClickHouse/metabase-clickhouse-driver#190]
### Describe the bug
IPv4 type field visualization starts with dash. 
![2023-09-08T16:59:55](https://github.com/ClickHouse/metabase-clickhouse-driver/assets/15222265/48939ee5-ee7e-4924-ae1f-89958fc4237d)

Is it expected? Why does it work like this? I didn't find any specifications ordering to show ip addr with dash.
Appreciate your reply.
### Steps to reproduce
select toIPv4('127.0.0.1')

### Expected behaviour
127.0.0.1

#### Environment
* metabase-clickhouse-driver version:
seems like 1.1.7
how can check this, btw?
* metabase-clickhouse-driver configuration:
default
* Metabase version:
v0.46.6
* OS:
CentOS 7
#### ClickHouse server
* ClickHouse Server version:
22.8.14 revision 54460

**Comment by phuntik** [comment]
Also might be worth mentioning.
I'm using mysql to store Metabase config. In metabase.metabase_field table there are multiple fields related to data types. I've tried to manually update some of them ipv4->string to mimic string behavior, but it didn't work either, showing dash anyways.
```sql
update metabase_field set base_type='type/Text' where id=53365;
update metabase_field set effective_type='type/Text' where id=53365;
update metabase_field set database_type='String' where id=53365;
```

**Comment by slvrtrn** [comment]
IIRC, that's how Java serializes these types by default (see [InetAddress.toString](https://stackoverflow.com/questions/12947435/inetaddress-tostring-returns-a-forward-slash)).
But it's easy enough to fix so it is less annoying :+1:

**Comment by slvrtrn** [comment]
@phuntik, fixed in https://github.com/ClickHouse/metabase-clickhouse-driver/releases/tag/1.2.2

**Comment by phuntik** [comment]
Thanks a lot, appreciate!
