### ISSUE TITLE
[FR] Option to use filters values without quotes

### ISSUE THREAD

**Issue by phuntik** [ClickHouse/metabase-clickhouse-driver#191]
Hello, hope you are doing well.

Intro
----
Pretty often there is a need to use granularity option while creating aggregating report with grouping by timerange to make it adaptive in terms of timerange selection. 
Example:
![image](https://github.com/ClickHouse/metabase-clickhouse-driver/assets/15222265/9e910f6d-dc49-4a12-8011-9354e4cff47d)

By typing any of given granularity option I make it possible to use single report for different timerange grouping options. 

In CH there is a perfect function present, allowing to optimize this query - [toStartOfInterval()](https://clickhouse.com/docs/en/sql-reference/functions/date-time-functions#tostartofintervaltime_or_data-interval-x-unit--time_zone)
I'd like to use it simply like this:
```sql
WITH
  toStartOfInterval(date_time, INTERVAL 1 {{Granularity}}) as ts
select 
    ts,
...
```
And it actually works, but..

Problem
----
Variable is passed to DB in quotes, generating next query:
```sql
WITH
  toStartOfInterval(date_time, INTERVAL 1 'Hour') as ts
```

And causing error:
`Code: 62. DB::Exception: Syntax error: failed at position 203 (''Hour'') (line 5, col 37): 'Hour') as ts`

Because CH expects word `Hour` without quotes.

Suggestion
----

To make it possible for report admin to define, how variable will be passed to DB.

p.s. I assume it might not be a FReq for driver and more related to Metabase itself. If so, I can do same request there.

Thanks.

**Comment by slvrtrn** [comment]
@phuntik, I asked the Metabase team, and they confirmed that it is a Metabase feature request.

**Comment by phuntik** [comment]
Thanks for reply. 
Can you clarify, please, do I have to create this FR for Metabase or is it an existing FR? 
Cause I didn't manage to find such a thing in opened issues, at least by brief search `is:issue is:open field filter in:title `
