### ISSUE TITLE
std::exception. Code: 1001, type: pqxx::broken_connection

### ISSUE THREAD

**Issue by LanMingjin** [ClickHouse/metabase-clickhouse-driver#201]
### Describe the bug
   I have set the socket_timeout and other configuration, but this error often happens. It will become normal after serveral 
times trying.

### Error log
std::exception. Code: 1001, type: pqxx::broken_connection, e.what() = Lost connection to the database server. (version 21.12.3.32 (official build)) , server ClickHouseNode [uri=http://XXX/XXX, options={compress=true,connection_timeout=100000,dataTransferTimeout=100000,maxCompressBufferSize=104857600,maxRetries=3,maxTotal=100000,socket_timeout=6000000

#### Environment
* metabase-clickhouse-driver version: 0.9.1
* Metabase version:0.45.21

**Comment by slvrtrn** [comment]
Could you try it with more recent versions?

- 0.9.1 is outdated. If upgrading Metabase to 0.47.x and using the latest driver release is not an option, I'd suggest at least 1.1.0, where the underlying JDBC driver was updated.
- Additionally, ClickHouse 21.12 is a rather old one, almost two years behind. Please consider upgrading there, too.
