### ISSUE TITLE
groupUniqArray() result true or false

### ISSUE THREAD

**Issue by jack-reso** [ClickHouse/metabase-clickhouse-driver#209]
### Steps to reproduce
1.i use groupUniqArray(toHour(gettime)) to find out unique hour in gettime ,but in metabase it result [false,false].
However when i use dbeaver,it't show [12,14] ,which mean gettime's unique hour is 12 and 14.

### Expected behaviour
true result show in dbeaver [12,14]
error result show in metabase [false,false].

#### Environment
* metabase-clickhouse-driver version:1.2.1
* metabase-clickhouse-driver configuration:
* Metabase version:0.47.4
* OS:docker

#### ClickHouse server
* ClickHouse Server version:22.9.5.25

**Comment by jack-reso** [comment]
colume:  gettime       uid
type:      Datetime64  String
data       2023-10-10 01:01:01 12edada
              2023-10-10 03:01:01 12edada
              2023-10-10 06:01:01 12edada

sql: select groupUniqArray(gettime) as hour_a, uid  from table group by uid

result in dbeaver: [1,3,4],12edada
result in metabase: [false,false,false],12edada

**Comment by jack-reso** [comment]
i run this from the sql query editor?

**Comment by slvrtrn** [comment]
@jack-reso, fixed in [1.3.1](https://github.com/ClickHouse/metabase-clickhouse-driver/releases/tag/1.3.1)

**Comment by jack-reso** [comment]
@slvrtrn thanks！
