### ISSUE TITLE
Error with trying to connect with multiple db in Databases field

### ISSUE THREAD

**Issue by mpanius** [ClickHouse/metabase-clickhouse-driver#215]
### Describe the bug

Trying to connect via ssl with correct rootcert in Additional JDBC connection string options (working nice with one database) not working

![image](https://github.com/ClickHouse/metabase-clickhouse-driver/assets/1970673/4ca070c9-3950-4f82-a4f9-3831937a2e0d)

### Error log

unable to find valid certification path to requested target, server ClickHouseNode [uri=https://myclick:8443/counters_jitsu, options={use_server_time_zone_for_dates=true,use_no_proxy=false,product_name=metabase/1.3.2}]@1427445778

#### Environment
* metabase-clickhouse-driver version: 1.3.2
* Metabase version: 0.48.3
* OS: Docker

**Comment by slvrtrn** [comment]
@mpanius, should be fixed in [1.3.3](https://github.com/ClickHouse/metabase-clickhouse-driver/releases/tag/1.3.3)
