### ISSUE TITLE
Add support for the "connection impersonation" Metabase feature

### ISSUE THREAD

**Issue by phil-schreiber** [ClickHouse/metabase-clickhouse-driver#219]
Hey, 
we're running an instance of metabase pro version
v1.47.8

We using clickhouse driver version:
1.2.4

On clickhouse databases the data access option `Impersonated` does not show up. On postgres sources the option does show up.

Any idea why we might not see the option for clickhouse?
It's a crucial feature for us and the main reason we bought into metabase pro.

**Comment by slvrtrn** [comment]
Unfortunately, I had to roll back the support of it because of https://github.com/ClickHouse/metabase-clickhouse-driver/issues/192

**Comment by phil-schreiber** [comment]
> Unfortunately, I had to roll back the support of it because of #192

Is it planned to fix it? Any ETA? Thanks in advance

**Comment by slvrtrn** [comment]
Apologies for the late reply. We are currently discussing whether it will be possible to memorize the session settings within the underlying JDBC driver, so it will not trigger the issues with the clustered on-premise deployments. 
Please stay tuned.

**Comment by slvrtrn** [comment]
@phil-schreiber, if everything goes well with the Java driver experiment, the ETA might be ClickHouse 24.3, best case scenario 24.2 - we will still need to make a minor adjustment to how the HTTP interface works.

**Comment by slvrtrn** [comment]
@phil-schreiber, sincere apologies for the delay. Here's an update.

- We have merged a new ClickHouse HTTP interface feature that allows to properly set a role for a particular statement, and that was the main blocker: https://github.com/ClickHouse/ClickHouse/pull/62669
- Here's the PR for the JDBC driver feature (https://github.com/ClickHouse/clickhouse-java/pull/1569), which relies on the changeset above
- I am going to finalize my testing with clusters with the updated JDBC driver and the latest ClickHouse build. There is a significant chance that everything will finally work with the impersonation feature and roles setting on the cluster setups.
- If all is good, this feature will work with ClickHouse 24.4+.

**Comment by slvrtrn** [comment]
Added in [1.5.0](https://github.com/ClickHouse/metabase-clickhouse-driver/releases/tag/1.5.0).
