### ISSUE TITLE
* in from clause causes syntax error

### ISSUE THREAD

**Issue by olafbuitelaar** [ClickHouse/metabase-clickhouse-driver#220]
### Describe the bug
when i try to create a question for ClickHouse, with a from function containing * with a variable, metabase seems to produce a syntax error.

### Steps to reproduce
create a question with query and variable XXX
select
columnA,
sum(arrayCount(x -> x == 'abc',Events.Name)) as eventAbc
from s3('https://s3.url.location/x/*/*/*/*/*.parquet','admin','default') as data_source
where XXX={{XXX}}
group by columnA

### Expected behaviour
the * in the function parameter (string) not causing syntax errors

#### Environment
- Metabase Version: v0.48.3
- Hosted on K8s

#### ClickHouse server
* ClickHouse Server version: 23.12.2.59 (official build)

https://github.com/metabase/metabase/issues/38051

**Comment by slvrtrn** [comment]
Similar behavior with MySQL, i.e., confirmed Metabase bug.

```sql
SELECT concat('/*/') 
WHERE 1=1 [[AND '42' = {{x}}]]
LIMIT 10
```

```
unknown escape sequence {{x}}
```

https://github.com/metabase/metabase/issues/38051 will be re-opened.
