### ISSUE TITLE
Versions confuse

### ISSUE THREAD

**Issue by VyachL05** [ClickHouse/metabase-clickhouse-driver#234]
### Describe the bug

Doc in Readme.md give example with version that is not exist.

### Steps to reproduce
![image](https://github.com/ClickHouse/metabase-clickhouse-driver/assets/93988186/d155cc82-5184-4681-87c1-4b998ffe5466)

![image](https://github.com/ClickHouse/metabase-clickhouse-driver/assets/93988186/bc624b6f-e09d-4231-ae4d-75a3152811a6)

**Comment by slvrtrn** [comment]
Nice catch; for some reason, this ended up in the main branch. I will fix it.
