### ISSUE TITLE
issue https://github.com/ClickHouse/metabase-clickhouse-driver/issues/224  happened again.

### ISSUE THREAD

**Issue by bladexxx** [ClickHouse/metabase-clickhouse-driver#248]
### Describe the bug

issue https://github.com/ClickHouse/metabase-clickhouse-driver/issues/224  happened again.
![image](https://github.com/ClickHouse/metabase-clickhouse-driver/assets/863963/36d691bb-9fa7-4b8a-9d47-789714090654)

#### Environment
* metabase-clickhouse-driver version: 1.5.0
* metabase-clickhouse-driver configuration:
* Metabase version: v0.49.14
* OS: Docker image

#### ClickHouse server
* ClickHouse Server version: 22.8.21.38 (official build)
* ClickHouse Server non-default settings, if any:
* `CREATE TABLE` statements for tables involved:
* Sample data for all these tables, use [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary

**Comment by slvrtrn** [comment]
> Steps to reproduce

This is important. The CI tests with an older version of ClickHouse (23.3) pass, which means that the correct function (`startsWith` instead of `startsWithUTF8`) is picked there.

Regardless, the current LTS version of ClickHouse is 23.8; please consider upgrading your ClickHouse deployment, as it is EOL already.

**Comment by bladexxx** [comment]
@slvrtrn thanks for your quick reply. is there any workaround way for this issue If we don't have any plans to upgrade at the moment?

**Comment by slvrtrn** [comment]
@bladexxx, I did not remove anything. I even have a CI workflow to test the driver with 23.3 - https://github.com/ClickHouse/metabase-clickhouse-driver/blob/master/.github/workflows/check.yml#L160-L165, which also runs the string filters tests that use either `startsWith`/`startsWithUTF8`, depending on the ClickHouse version.
