### ISSUE TITLE
Arrays make select 30 times slower 

### ISSUE THREAD

**Issue by picachuloves** [ClickHouse/metabase-clickhouse-driver#257]
### Describe the bug
Arrays make select 60 times slower.
I got a table with 2000 rows, 44 not array columns and 6 array columns
If we select on this table with arrays , "select * limit 2000" takes up to 1,5 minutes
But I can see in clickhouse logs that this query takes less then a second
Also if I make a view with arrayStringConcat over Array columns "select * limit 2000" takes 1,5 seconds
I see in the log 12000 exceptions 
`ERROR driver.clickhouse-qp :: Failed to get the inner type of the array column `
12000/2000 (limit 2000) = 6 = amount of Array columns
So handling this exceptions makes perfomance much slower 
### Steps to reproduce
1. Create table with arrays 
2. Check time on "select *" on this table
3. Create view with arrayStringConcat over Array columns
4. Check  time on "select *" on this view

### Expected behaviour
Exceptions handling does not affect select perfomance 

### Error log
`ERROR driver.clickhouse-qp :: Failed to get the inner type of the array column"`

#### Environment
* metabase-clickhouse-driver version: 1.4.0 
* metabase-clickhouse-driver configuration: socket_timeout=300000
* Metabase version: v0.49.7

#### ClickHouse server
* ClickHouse Server version: 23.8.14.6

**Comment by slvrtrn** [comment]
This is clearly coming from this part: https://github.com/ClickHouse/metabase-clickhouse-driver/blob/1.50.1/src/metabase/driver/clickhouse_qp.clj#L524-L532, which uses the default JDBC API to obtain the required info.
Can you please provide the problematic table DDL so I can properly test why it throws?

**Comment by picachuloves** [comment]
Sure, here it is

**Comment by picachuloves** [comment]
Yes, it's okay to update for me. Which version I should update to?

**Comment by slvrtrn** [comment]
@picachuloves, this should be fixed in [1.50.2](https://github.com/ClickHouse/metabase-clickhouse-driver/releases/tag/1.50.2); Metabase 0.50.x is required, e.g., [v0.50.13](https://github.com/metabase/metabase/releases/tag/v0.50.13).

**Comment by picachuloves** [comment]
Thank you!
