### ISSUE TITLE
Quote roles if needed in SET ROLE

### ISSUE THREAD

**Issue by sharankow** [ClickHouse/metabase-clickhouse-driver#262]
### Describe the bug

For connection impersonation, we are populating `database_role` user attribute to contain the list of roles associated with the user to access tables in Clickhouse. The SET ROLE [statement](https://github.com/ClickHouse/metabase-clickhouse-driver/blob/master/src/metabase/driver/clickhouse.clj#L283) currently only supports roles that don't have a special character in them (`-` in our case) and fails when such a role is passed to it.  

It could be worked around by quoting the roles in the user attribute, but this is undesired.

We fixed it in our forked version of the driver by splitting the list of roles by their separator (`,`) and adding quotes around them if needed, and it seemed to work as expected.

### Steps to reproduce
1. Enable connection impersonation in Metabase
2. Create `database_role` user attribute and add a role with a special character as the value (in the screenshot below we set the value of `database_role` to `data-engineer,readonly`)
3. Fire a query and that gives this error
![Screenshot 2024-08-19 at 16 25 27](https://github.com/user-attachments/assets/d9d31c0b-f4f8-4d0c-9264-5c120f3945fa)

### Expected behaviour
Metabase should be able to query Clickhouse as an impersonated user with the user roles listed in `database_role` user attribute

#### Environment
* metabase-clickhouse-driver version: v1.50.13
* Metabase version: v1.50.13

#### ClickHouse server
* ClickHouse Server version: 24.7

**Comment by slvrtrn** [comment]
> We fixed it in our forked version of the driver by splitting the list of roles by their separator (,) and adding quotes around them if needed, and it seemed to work as expected.

Would you like to make a PR?
