### ISSUE TITLE
Toggling `allow_experimental_analyzer=0/1`

### ISSUE THREAD

**Issue by lainiwa** [ClickHouse/metabase-clickhouse-driver#271]
Hi!

I'm struggling to toggle `allow_experimental_analyzer=1` by adding it to `Additional JDBC connection string options`.
All queries still run with the default/`0` `allow_experimental_analyzer` flag.
I see it was hard-coded to `0` [until some time ago](https://github.com/ClickHouse/metabase-clickhouse-driver/commit/01ecc5fbcc53d007b9a7357bd358428a4f3bc738#diff-735848a5036ee0dc1ed67d137c46538d89d61d8bb0da9c75a4da2ad749c64f31R77), but I'm using plugin version `1.50.6`, which (as far as I imagine) should not re-write the setting.

I want to toggle the analyzer independently of the clickhouse version.
What am I missing?

Metabase `v0.50.27`, clickhouse `23.8.16`

**Comment by slvrtrn** [comment]
@lainiwa, this is indeed very annoying, and the additional JDBC options don't help in this case. A separate field to override that will be added after https://github.com/ClickHouse/metabase-clickhouse-driver/pull/272

**Comment by slvrtrn** [comment]
@lainiwa, can you please try https://github.com/ClickHouse/metabase-clickhouse-driver/releases/tag/1.50.7?

**Comment by lainiwa** [comment]
Looks good, thank you!
