### ISSUE TITLE
SSL certificates for connection

### ISSUE THREAD

**Issue by dzarlax** [ClickHouse/metabase-clickhouse-driver#41]
Hi,
I'm trying to connect to Yandex.Cloud MDB Clickhouse from Metabase, but gets an error:

`ru.yandex.clickhouse.except.ClickHouseUnknownException: ClickHouse exception, code: 1002, host: {host}, port: 8443; sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target`

In additional parameters I add:

`ssl=true&sslrootсert=/usr/local/share/ca-certificates/Yandex/YandexInternalRootCA.crt`

**Comment by dzarlax** [comment]
Here is an error on clickhouse side:

`{
  "component": "ServerErrorHandler",
  "hostname": "{host}",
  "message": "Poco::Exception. Code: 1000, e.code() = 0, e.displayText() = SSL Exception: error:14037416:SSL routines:ACCEPT_SR_KEY_EXCH:sslv3 alert certificate unknown (version 19.14.7.15 (official build)",
  "severity": "Error",
  "thread": "50",
  "query_id": ""
}`

**Comment by dzarlax** [comment]
I've found where this error was fixed - https://github.com/ClickHouse/clickhouse-jdbc/pull/365
Maybe JDBC should be updated. @enqueue

**Comment by enqueue** [comment]
Hi @dzarlax, good job identifying the cause of the issue! 👏 In trying to make the driver work with Metabase 0.34, we will also be updating JDBC driver. Hopefully this will solve your SSL issue. If you want, you can try version 0.7-BETA. It is BETA because

1. the code uses proprietary JDBC driver code
2. the driver does not pass all MetaBase integration tests, yet.

**Comment by enqueue** [comment]
@dzarlax did you try to connect using driver version 0.7.0? I personally do not have any experience setting up SSL connection between Metabase and ClickHouse.

**Comment by dzarlax** [comment]
Finally YES, thanks a lot!!

**Comment by vmoshikov** [comment]
I invite you to share your experience with the community. Getting connection errors in Docker and local Metabase

**Comment by dzarlax** [comment]
> @dzarlax I invite you to share your experience with the community. Getting connection errors in Docker and local Metabase

How can I help?

**Comment by vmoshikov** [comment]
@dzarlax What are the use of the SSL parameters to connect to the ClickHouse cluster in Yandex.Cloud? 
You use .pem or .crt file?

**Comment by egorperesada** [comment]
> All perfectly. I threw the certificate into docker and registered the parameters `ssl=true&sslrootcert=/usr/local/share/ca-certificates/Yandex/YandexInternalRootCA.crt`

Where can I put this parameters? I don't see any "additional parameters" or etc to add them
![Screenshot 2022-06-21 at 11 06 44](https://user-images.githubusercontent.com/36980920/174728000-25b12767-c0e2-4399-929f-09966ff1fd89.png)
 in metabase 0.43.3

**Comment by kartaris** [comment]
> > All perfectly. I threw the certificate into docker and registered the parameters `ssl=true&sslrootcert=/usr/local/share/ca-certificates/Yandex/YandexInternalRootCA.crt`
> 
> Where can I put this parameters? I don't see any "additional parameters" or etc to add them in metabase 0.43.3 and driver 0.8.1 ![Screenshot 2022-06-21 at 11 06 44](https://user-images.githubusercontent.com/36980920/174728000-25b12767-c0e2-4399-929f-09966ff1fd89.png) Ω

Still have no idea how to configure ClickHouse database with setting an SSL certificate through UI =(
There is no such option.

**Comment by slvrtrn** [comment]
@kartaris 
can you please try this:

![image](https://user-images.githubusercontent.com/3175289/217065737-115c77eb-18a9-419f-b73f-1291390efc72.png)

My tests show no issues connecting to a secured ClickHouse instance with Basic TLS. I also verified that it works from the UI.

I run Metabase as a Docker container, and a sample config might look like this:

```yml
  metabase:
    image: metabase/metabase:v0.45.1
    container_name: metabase-with-clickhouse-driver
    ports:
      - '3000:3000'
    volumes:
      - '../../../resources/modules/clickhouse.metabase-driver.jar:/plugins/clickhouse.jar'
      - './.docker/clickhouse/single_node_tls/certificates/ca.crt:/certs/ca.crt'
```

So, the server cert is mounted as `/certs/ca.crt`, so I'll just put

```
sslrootcert=/certs/ca.crt
```

In the additional options input. Make sure that you have "Use secure connection (SSL)" ticked as well.

**Comment by kartaris** [comment]
> @kartaris can you please try this:
> 
> ![image](https://user-images.githubusercontent.com/3175289/217065737-115c77eb-18a9-419f-b73f-1291390efc72.png)
> 
> My tests show no issues connecting to a secured ClickHouse instance with Basic TLS. I also verified that it works from the UI using the latest release (1.0.1).
> 
> I run Metabase as a Docker container, and a sample config might look like this:
> 
> ```yaml
>   metabase:
>     image: metabase/metabase:v0.45.1
>     container_name: metabase-with-clickhouse-driver
>     ports:
>       - '3000:3000'
>     volumes:
>       - '../../../resources/modules/clickhouse.metabase-driver.jar:/plugins/clickhouse.jar'
>       - './.docker/clickhouse/single_node_tls/certificates/ca.crt:/certs/ca.crt'
> ```
> 
> So, the server cert is mounted as `/certs/ca.crt`, so I'll just put
> 
> ```
> sslrootcert=/certs/ca.crt
> ```
> 
> In the additional options input. Make sure that you have "Use secure connection (SSL)" ticked as well.

Yep. I found the way to do it using API(by adding the `ssl=true&sslrootcert=/usr/local/share/ca-certificates/Yandex/YandexInternalRootCA.crt` to the additional-options in POST request) and also using the method you have provided. But there is no such option to set the path to the certificate through UI even if "Use secure connection (SSL)" ticked.

<img width="721" alt="image" src="https://user-images.githubusercontent.com/10552394/217073580-1d5eaa5d-3fa4-4c81-8ea2-136406fc4f5e.png">

And as an example how it's done in PostgreSQL. User may set the path to the certificate and even upload it through API.

<img width="687" alt="image" src="https://user-images.githubusercontent.com/10552394/217074198-83312d9f-8931-40f2-bd41-e7ae2bb258a2.png">

**Comment by slvrtrn** [comment]
@kartaris what plugin version do you use?

**Comment by kartaris** [comment]
> @kartaris what plugin version do you use?
> Additional JDBC options (and advanced connection settings) were restored in [0.8.3 IIRC](https://github.com/ClickHouse/metabase-clickhouse-driver/pull/109).

Sorry, my bad. I were using 0.8.1 version. Updated to 1.0.1 and now I see it can be done through UI. But it's not as clear as in PostgreSQL plugin

**Comment by slvrtrn** [comment]
@kartaris, for sure, I see that we should go Postgres way here. 

I've added an issue to the backlog: https://github.com/ClickHouse/metabase-clickhouse-driver/issues/136

If you have time, please feel free to contribute.
