### ISSUE TITLE
Substring Broken (1-based versus 0-based)

### ISSUE THREAD

**Issue by enqueue** [ClickHouse/metabase-clickhouse-driver#59]
The substring function does not work as expected for custom fields. 

![Screenshot_20201215_150412](https://user-images.githubusercontent.com/5407006/102225035-01976a80-3ee7-11eb-8081-4b8d4fd57cb9.png)

In Metabase, the indices seem to be 0-based, whereas ClickHouse [substring function](https://clickhouse.tech/docs/en/sql-reference/functions/string-functions/#substring) expects indices to be 1-based:

> Character indexing starts from one (as in standard SQL).

From `clickhouse-server.err.log`:
```
Indices in strings are 1-based: while executing 'FUNCTION substring(username :: 3, 0 :: 5, 10 :: 6) -> substring(username, 0, 10) String : 7'
```

Let‘s see what Metabase maintainers agree on in metabase/metabase#12445

**Comment by slvrtrn** [comment]
Resolved as of Metabase 0.46 (see https://github.com/metabase/metabase/pull/28067)

![image](https://github.com/ClickHouse/metabase-clickhouse-driver/assets/3175289/14e7b9b5-eb4b-41a8-b93a-6ede01416212)

![image](https://github.com/ClickHouse/metabase-clickhouse-driver/assets/3175289/324e0905-0cd0-4c62-ba6a-41efd4f5cfe5)
