### ISSUE TITLE
In the Metabase database,   the 'type/Decimal'  changes to 'type/Text' ,  in the effective_type  field of table metabase_field

### ISSUE THREAD

**Issue by v-wx-v** [ClickHouse/metabase-clickhouse-driver#91]
In the Metabase database,   the 'type/Decimal'  changes to 'type/Text' ,  in the effective_type  of table metabase_field

**Comment by v-wx-v** [comment]
Metabase v 0.42.4
Clickhouse v 21

**Comment by slvrtrn** [comment]
Should be fixed as of 1.2.0.
