### ISSUE TITLE
Only show tables and schema for database given in connection settings

### ISSUE THREAD

**Issue by nilaymk** [ClickHouse/metabase-clickhouse-driver#96]
Scenario :
- My clickhouse instance has 2 databases `my_lovely_db` and `my_horrid_db`
- While creating a new database connection via "Admin settings", I have provided a value in "Database" field (e.g. `my_lovely_db`)
- When I try to admin (e.g. update Data Model) or query (e.g create Questions), it shows both databases as `schemas` even though I have specified `my_lovely_db` in connection.

Expected:
- it should only show the `my_lovely_db` schema
- i.e. When a database is provided in the connection string, it should only show that as a schema for that connection.

**Comment by enqueue** [comment]
Thanks @nilaymk for the report. The discovery of the schemas is a fragile point, and the concepts "schema", "catalog" or "table" are not used consistently in MetaBase and the ClickHouse JDBC driver. We will have to work around this issue.

**Comment by nilaymk** [comment]
This is now fixed. See here: https://github.com/ClickHouse/metabase-clickhouse-driver/issues/121
